apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: ckad
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 8501
  selector:
    app: frontend
  type: ClusterIP
status:
  loadBalancer: {}
